# Generated by Django 4.1 on 2022-08-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_employees_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='coeffitient',
            new_name='coefficient',
        ),
    ]
