# Generated by Django 4.1 on 2022-08-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_null_parent'),
        ('employees', '0004_add_archived_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='objects.object'),
            preserve_default=False,
        ),
    ]
