# Generated by Django 4.1 on 2022-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_to_employee',
            field=models.BooleanField(default=False),
        ),
    ]
