# Generated by Django 4.1 on 2022-08-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_employees_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_paid_by_card', models.BooleanField(default=False)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.masterprocedure')),
            ],
            options={
                'db_table': 'procedure_purchases',
            },
        ),
    ]
