# Generated by Django 4.1 on 2022-08-19 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_material_model'),
        ('employees', '0001_employees_models'),
        ('purchases', '0001_purchace_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.masterprocedure')),
            ],
            options={
                'db_table': 'purchase_procedure',
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='procedure',
        ),
        migrations.AddField(
            model_name='purchase',
            name='procedures',
            field=models.ManyToManyField(related_name='procedures', through='purchases.PurchaseProcedure', to='employees.masterprocedure'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UsedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.material')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='purchases.purchaseprocedure')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseprocedure',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
