# Generated by Django 4.1 on 2022-08-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_archived_field'),
        ('purchases', '0003_alter_usedmaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='procedures',
            field=models.ManyToManyField(related_name='purchases', through='purchases.PurchaseProcedure', to='employees.masterprocedure'),
        ),
    ]
