# Generated by Django 4.1 on 2022-08-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_material_price_stock_productmaterial'),
        ('purchases', '0004_relation_name_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='procedures',
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='inventory.productmaterial'),
        ),
    ]
