# Generated by Django 4.1 on 2022-08-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_coefficient_alter_employee_object'),
        ('purchases', '0005_remove_purchase_procedures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='procedures',
            field=models.ManyToManyField(related_name='purchases', through='purchases.PurchaseProcedure', to='employees.masterprocedure'),
        ),
    ]
