# Generated by Django 4.1 on 2022-08-31 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productmaterial_material'),
        ('purchases', '0006_purchase_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.productmaterial'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='purchases.purchaseprocedure'),
        ),
    ]
