# Generated by Django 4.1 on 2022-08-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_usedmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usedmaterial',
            table='used_material',
        ),
    ]
