# Generated by Django 4.1 on 2022-09-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_usedmaterial_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usedmaterial',
            table='used_materials',
        ),
    ]
