# Generated by Django 4.1 on 2022-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_procedure_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
