# Generated by Django 4.1 on 2022-08-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_add_objects'),
        ('procedures', '0002_add_archived_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='objects.department'),
            preserve_default=False,
        ),
    ]
