# Generated by Django 4.1 on 2022-09-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='material_name')),
                ('unit', models.CharField(choices=[('GR', 'Gramms'), ('PC', 'Pieces')], max_length=3, verbose_name='material_measurment_units')),
                ('archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='objects.object')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='material_price')),
                ('amount', models.IntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.material')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.material')),
            ],
            options={
                'db_table': 'product_material',
            },
        ),
    ]
