# Generated by Django 4.1 on 2022-08-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_add_objects'),
        ('inventory', '0002_alter_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='objects.object'),
            preserve_default=False,
        ),
    ]
