# Generated by Django 4.1 on 2022-08-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_material_price_stock_productmaterial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmaterial',
            table='product_material',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stocks',
        ),
    ]
