# Generated by Django 4.1 on 2022-08-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productmaterial_table_alter_stock_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.material'),
        ),
    ]
